In [1]:
#1.	Write a Python Program to Add Two Matrices?
# 2.Write a Python Program to Multiply Two Matrices?
# 3.Write a Python Program to Transpose a Matrix?
# 4.Write a Python Program to Sort Words in Alphabetic Order?
# 5.Write a Python Program to Remove Punctuation From a String?

In [15]:
#1.	Write a Python Program to Add Two Matrices?

import numpy as np

m1 = np.array([[1,2],[4,5]])

m2 = np.array([[3,4],[7,8]])

print(m1+m2)



[[ 4  6]
 [11 13]]


In [16]:
# 2.Write a Python Program to Multiply Two Matrices?
import numpy as np

m1 = np.array([[1,2],[4,5]])

m2 = np.array([[3,4],[7,8]])

mul = m1@m2

print(mul)

[[17 20]
 [47 56]]


In [26]:
# 3.Write a Python Program to Transpose a Matrix?
import numpy as np

m1 = np.array([[1,2,3,4,6]])
print(f"Before the Transpose the matrix is {m1}")
print(" \nAfter the Transpose the given  Matrix\n ", m1.T)

Before the Transpose the matrix is [[1 2 3 4 6]]
 
After the Transpose the given  Matrix
  [[1]
 [2]
 [3]
 [4]
 [6]]


In [10]:
# 4.Write a Python Program to Sort Words in Alphabetic Order?
x = input("Enter the Words or Sentence of the string")
l = x.split(' ') 
l.sort()

print(f"ths sorted string is {l}")


Enter the Words or Sentence of the stringthis is string
ths sorted string is ['is', 'string', 'this']


In [2]:
# 5.Write a Python Program to Remove Punctuation From a String?

test_str = input("Enter the String of your Choice")
 
print("The original string is : " + test_str)
 
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
 
for ele in test_str:
    if ele in punc:
        test_str = test_str.replace(ele, "")
 
print("The string after punctuation filter : " + test_str)

Enter the String of your ChoicePicen kldjsflj $$s lkjsfkjg&& lajsdf
The original string is : Picen kldjsflj $$s lkjsfkjg&& lajsdf
The string after punctuation filter : Picen kldjsflj s lkjsfkjg lajsdf
